---
title: "Control_data_rozen_vs_jill"
author: "Xinyi"
date: "2023-02-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### prepare packages 
```{r, libraries, echo=TRUE, message=FALSE}
# CRAN packages
library(ICAMS)
#BiocManager::install("ICAMS")
library(philentropy)
library(factoextra)
library(gplots)
library(nloptr)

# Other
devtools::load_all(".")
library(BSgenome.Hsapiens.1000genomes.hs37d5)
```
# Functions for this File 
```{r}
pcat <- function(catalog) {
  par(pin = c(3*ncol(catalog), 1))
  par(mfrow = c(ncol(catalog), 1))
  par(mar = c(2, 4, 4, 2))
  par(cex = 0.8)
  par(cex.main = 1.4) 
  xlabels <- FALSE
  for (i in 1:ncol(catalog)) {
    if (FALSE && i == ncol(catalog)) { # FALSE an experiment
      xlabels <- TRUE
      par(mar = c(4.5, 4, 3, 2))
    }
    
    ICAMS::PlotCatalog(catalog[ , i, drop = FALSE],
                       upper = (i == 1),
                       xlabels = xlabels)
  }
}
```

```{r}
convert_base <- function(x){
  if (x == "A")
    ret <- "T"
  else if (x == "C")
    ret <- "G"
  else if (x == "G")
    ret <- "C"
  else if (x == "T")
    ret <- "A"
  else{
    message("Incorrent input")
    ret <- 0
  }
    
  return(ret)
}
```

```{r}
Jill_to_SBS96 <- function(input_table){
  subs <- input_table[,c("pre_context","Ref","rear_context","Alt")]
  for (i in 1:nrow(input_table)){
    if (subs[i,2] == "A" | subs[i,2] =="G"){
      tmp1 <- convert_base(subs[i,1])
      tmp2 <- convert_base(subs[i,2])
      tmp3 <- convert_base(subs[i,3])
      tmp4 <- convert_base(subs[i,4])
      subs[i,1] <- tmp3
      subs[i,2] <- tmp2
      subs[i,3] <- tmp1
      subs[i,4] <- tmp4
    }
  }
  subs.pasted <- apply(subs, MARGIN = 1, function(x){paste0(x[1], x[2], x[3], x[4])})
  SBS96.template <- c("ACAA", "ACCA", "ACGA", "ACTA", "CCAA", "CCCA", "CCGA", "CCTA", 
                      "GCAA", "GCCA", "GCGA", "GCTA", "TCAA", "TCCA", "TCGA", "TCTA", 
                      "ACAG", "ACCG", "ACGG", "ACTG", "CCAG", "CCCG", "CCGG", "CCTG", 
                      "GCAG", "GCCG", "GCGG", "GCTG", "TCAG", "TCCG", "TCGG", "TCTG",
                      "ACAT", "ACCT", "ACGT", "ACTT", "CCAT", "CCCT", "CCGT", "CCTT", 
                      "GCAT", "GCCT", "GCGT", "GCTT", "TCAT", "TCCT", "TCGT", "TCTT", 
                      "ATAA", "ATCA", "ATGA", "ATTA", "CTAA", "CTCA", "CTGA", "CTTA", 
                      "GTAA", "GTCA", "GTGA", "GTTA", "TTAA", "TTCA", "TTGA", "TTTA", 
                      "ATAC", "ATCC", "ATGC", "ATTC", "CTAC", "CTCC", "CTGC", "CTTC", 
                      "GTAC", "GTCC", "GTGC", "GTTC", "TTAC", "TTCC", "TTGC", "TTTC", 
                      "ATAG", "ATCG", "ATGG", "ATTG", "CTAG", "CTCG", "CTGG", "CTTG", 
                      "GTAG", "GTCG", "GTGG", "GTTG", "TTAG", "TTCG", "TTGG", "TTTG") 
  subs.spectra <- rep(0,96)
  names(subs.spectra) <- SBS96.template
  
  # count occurrence 
  for (i in subs.pasted){
    subs.spectra[i] <- subs.spectra[i] + 1
  }
  
  subs.cat <- as.catalog(as.matrix(subs.spectra), ref.genome = "GRCh37", region = "genome", catalog.type = "counts" , infer.rownames = TRUE)
  
  return(subs.cat)
}
```

### Prepare Controls
##### Load the controls from vcfs (our data)
```{r}
dnames <- c(
  "HepG2_Control",
  "HepG2-Hamster-S9",
  "HepG2-RatS9",
  "HepG2-RatS9-DMSO",
  "MCF10A_Control",
  "MCF10A-Hamster-S9",
  "MCF10A-RatS9",
  "MCF10A-RatS9-DMSO"
)

hack_ref_genome <- function(dname) {
  if (grepl("_Control", dname)) {
    return("GRCh37")
  } else {
    return("hg38")
  }
}

get_spectra <- function(dd) {
  
  vcfs <- list.files(path = file.path("../data/controls_data_vcf/", dd), 
                     full.names = TRUE)
  return(
    ICAMS::VCFsToCatalogs(
      vcfs,
      ref.genome = hack_ref_genome(dd),
      variant.caller = "strelka",
      region = "genome"))
}

rozen_ctrl_spectra <- lapply(dnames, get_spectra)
names(rozen_ctrl_spectra) = dnames

rozen_ctrl_s96 <- lapply(dnames, function(dd) {rozen_ctrl_spectra[[dd]]$catSBS96} )
names(rozen_ctrl_s96) = dnames
```

##### Load the controls (Jill's data）
Read Input from Jill Kucab's data
```{r}
subs.all <- read.table("Jill_Kucab_paper/Jill_denovo_subclone_subs_final.txt",header = TRUE, sep ="\t")
```

```{r}
# Creating a table to map MSM code to sig.name 
MSM_table <- read.table("Jill_Kucab_paper/MSM_table", header = TRUE, sep = "\t") #, col.names=c("Sample.Name", "Treatment") )
names <- gsub(" ", ".",MSM_table[,2])
names <- gsub("\\(", ".",names)
names <- gsub("\\)", ".",names)
names <- gsub("\\+", ".",names)
names <- gsub(",",".",names)
names <- gsub("-",".",names)
MSM_table[,2] <- names
```

```{r}
# in the MSM table provided, two MSM codes are mapped to the same signature name
# MSM0.11	Temozolomide..200.uM.			
# MSM0.75	Temozolomide..200.uM.
# in Signature names, only one is named as Temozolomide..200.uM..1
# Here we assume that MSM0.75 is named as Temozolomide..200.uM..1
MSM_table[MSM_table[1]=="MSM0.75",2] <- "Temozolomide..200.uM..1"
```

```{r}
by.sample <- split(subs.all, subs.all$Sample.Name)
all.spectra <- lapply(by.sample, Jill_to_SBS96)
alls <- do.call(cbind, all.spectra)
rownames(MSM_table) <- MSM_table$Sample.Name
colnames(alls) <- paste(colnames(alls), MSM_table[colnames(alls), "Treatment"])
ICAMS::PlotCatalogToPdf(alls, "jill.all.pdf")
ICAMS::PlotCatalogToPdf(alls[ , grepl("Control", colnames(alls), fixed = TRUE)], "jill.control.pdf")
```


### Generate BG info 
```{r}
all.controls <- alls[ , grepl("Control", colnames(alls), fixed = TRUE)]
bg.media <- MakeBackgroundInfo(all.controls)
```

```{r, fig.height=1.5, fig.width=10}
colnames(bg.media$background.sig) <- "Jill's controls"
pcat(bg.media$background.sig)
```

```{r,fig.height=3, fig.width=10}
# cannot mix catalog with different refernce genome 

hepg2.else.bg <- MakeBackgroundInfo(cbind(hepg2.HS9.spec, hepg2.RS9.spec, hepg2.RS9_DMSO.spec))
mcf10a.else.bg <- MakeBackgroundInfo(cbind(mcf10a.HS9.spec, mcf10a.RS9.spec, mcf10a.RS9_DMSO.spec))
colnames(hepg2.else.bg$background.sig) <- "hepg2.else.bg"
colnames(mcf10a.else.bg$background.sig) <- "mcf10a.else.bg"
pcat(cbind(hepg2.else.bg$background.sig, mcf10a.else.bg$background.sig))
```
#### HepG2
```{r,fig.height=1.5, fig.width=10, echo=FALSE}
# hepg2.bg <- MakeBackgroundInfo(hepg2.ctrl.spec)$background.sig
# hepg2.HS9.bg <- MakeBackgroundInfo(hepg2.HS9.spec)$background.sig
# hepg2.RS9.bg <- MakeBackgroundInfo(hepg2.RS9.spec)$background.sig
# hepg2.RS9_DMSO.bg <- MakeBackgroundInfo(hepg2.RS9_DMSO.spec)$background.sig


rozen.bg <- lapply(rozen_ctrl_s96, MakeBackgroundInfo)
names(rozen.bg) <- names(rozen_ctrl_s96)



```


# Signatures with Jill's data: rozen method VS jill method
```{r}

# Jill separated data
load("Jill_Kucab_paper/Jill.all.compound.sep.Rdata")
load("Jill_Kucab_paper/Jill.all.cosine.Rdata")

# Rozen separated data
load("all.separated.Rdata")

# Jill signature data
sig.all <- read.table("Jill_Kucab_paper/Jill_Mutagen53_sub_signature.txt",header = TRUE, sep ="\t")

```

Processing of Jill's signature data for mapping 
```{r}
# REMOVE X IN "X1.8.DNP..0.125.uM." for sig.name column names for MSM_table matching 
for (i in 1:length(colnames(sig.all))){
  if (substring(colnames(sig.all)[i], 1, 1) =="X")
    colnames(sig.all)[i] <- substring(colnames(sig.all)[i],2)
}
```


```{r, fig.width=10, fig.height=1.5}
interesting_compounds <- names(all.cosine[all.cosine < 0.99])

i <- interesting_compounds[8]
for (i in interesting_compounds){
  pcat(as.catalog(sig.all[,i, drop = FALSE],catalog.type = "counts.signature", infer.rownames = TRUE))
  pcat(all.compound.sep[[i]]$inferred.target.sig.as.catalog)
  print(all.cosine[i])
}
```

# Compare Singature with shared compounds
```{r}
print(all.cosine[grep("Cisplatin",names(all.cosine))])
print(all.cosine[grep("Carboplatin",names(all.cosine))])
jill.cis.sep <- all.compound.sep[grep("Cisplatin",names(all.cosine))]
jill.car.sep <- all.compound.sep[grep("Carboplatin",names(all.cosine))]
```


```{r, fig.height=9}
colnames(jill.cis.sep$Cisplatin..3.125.uM.$inferred.target.sig.as.catalog) <- paste("MSM0.7","Cisplatin..3.125.uM.", sep="_")
colnames(jill.cis.sep$Cisplatin..12.5.uM.$inferred.target.sig.as.catalog) <- paste("MSM0.83","Cisplatin..12.5.uM.", sep="_" )

  
cis.all.sig <- cbind(jill.cis.sep$Cisplatin..3.125.uM.$inferred.target.sig.as.catalog,
           as.catalog(sig.all[,"Cisplatin..3.125.uM.", drop = FALSE], catalog.type = "counts.signature", infer.rownames = TRUE),
           jill.cis.sep$Cisplatin..12.5.uM.$inferred.target.sig.as.catalog,
           as.catalog(sig.all[,"Cisplatin..12.5.uM.", drop = FALSE], catalog.type = "counts.signature", infer.rownames = TRUE),
           all.separated$HepG2.cis.sig$inferred.target.sig.as.catalog,
           all.separated$MCF10A.cis.sig$inferred.target.sig.as.catalog)

pcat(cis.all.sig)
```

```{r, fig.height=6, fig.width=6}
cosine.sim <- suppressMessages(
  philentropy::distance(t(cis.all.sig), method = "cosine"))
  
rownames(cosine.sim) <- colnames(cis.all.sig)
colnames(cosine.sim) <- colnames(cis.all.sig)
gplots::heatmap.2(x = cosine.sim,
                  dendrogram = "column",
                  margins = c(18, 18),
                  cex.axis = 6,
                  symm = TRUE,
                  trace = "none")

```

```{r, fig.height=6}
colnames(jill.car.sep$Carboplatin..5.uM.$inferred.target.sig.as.catalog) <- paste("MSM0.72","Carboplatin..5.uM.", sep="_")

  
car.all.sig <- cbind(jill.car.sep$Carboplatin..5.uM.$inferred.target.sig.as.catalog,
           as.catalog(sig.all[,"Carboplatin..5.uM.", drop = FALSE], catalog.type = "counts.signature", infer.rownames = TRUE),
           all.separated$HepG2.car.sig$inferred.target.sig.as.catalog,
           all.separated$MCF10.car.sig$inferred.target.sig.as.catalog)

pcat(car.all.sig)
```
```{r,fig.height=6, fig.width=6}
cosine.sim <- suppressMessages(
  philentropy::distance(t(car.all.sig), method = "cosine"))
  
rownames(cosine.sim) <- colnames(car.all.sig)
colnames(cosine.sim) <- colnames(car.all.sig)
gplots::heatmap.2(x = cosine.sim,
                  dendrogram = "column",
                  margins = c(20, 20),
                  cex.axis = 4,
                  symm = TRUE,
                  trace = "none")

```



